pluginManagement {
	repositories {
		mavenLocal()
		google()
		mavenCentral()
		maven { url 'https://jitpack.io' }
		gradlePluginPortal()
	}
}
dependencyResolutionManagement {
	repositories {
		mavenLocal()
		google()
		mavenCentral()
		maven { url 'https://jitpack.io' }
		gradlePluginPortal()
	}
}

rootProject.name = "本地聊天"
include ':app'
